config/routes.rb
Falcon::Application.routes.draw do

  resources :projects do
    resources :issues
  end

  devise_for :users

  root :to => 'projects#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/issue.rb
class Issue
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Taggable

  field :title
  field :description

  #associations#
  belongs_to :owner, :class_name => "User"
  belongs_to :project

  #validations#
  validates :title, :presence => true
  validates :project_id, :presence => true

end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :description

  #associations#
  belongs_to :owner, :class_name => "User"
  has_many :issues

  #validations#
  validates :title, :presence => true
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json

  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @issues = @project.issues
    respond_with(@issues)
  end

  def show
    @issue = Issue.find(params[:id])
    respond_with(@issue)
  end

  def new
    @issue = Issue.new(:project => Project.find(params[:project_id]))
    respond_with(@issue)
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def create
    @issue = Issue.new(params[:issue])
    @issue.owner = current_user
    @issue.project = Project.find(params[:project_id])
    @issue.save
    respond_with(@issue.project, @issue)
  end

  def update
    @issue = Issue.find(params[:id])
    @issue.update_attributes(params[:issue])
    respond_with(@issue.project, @issue)
  end

  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy
    respond_with(@issue.project, @issue)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new params[:project]
    @project.owner = current_user
    @project.save

    respond_with @project
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title = "")
    content_for(:title) { page_title }  
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/issues/_form.html.haml
= simple_form_for([@issue.project, @issue ]) do |f|
  = f.error_notification
  .inputs
    = f.input :title
    = f.input :description, :as => :text
    = f.input :tags

  .actions
    = f.button :submit

app/views/issues/edit.html.haml
-title @issue.title
= render 'form'

app/views/issues/index.html.haml
-title @project.title

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th

  - @issues.each do |issue|
    %tr
      %td= issue.title
      %td= issue.description
      %td= link_to 'Show', [@project, issue]
      %td= link_to 'Edit', edit_project_issue_path(@project, issue)
      %td= link_to 'Destroy', [@project, issue], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Issue', new_project_issue_path(@project)

app/views/issues/new.html.haml
-title "New issue"

= render 'form'

app/views/issues/show.html.haml
-title @issue.title
%p
  %b Description:
  = @issue.description

= link_to 'Edit', edit_project_issue_path(@issue)
\|
= link_to 'Back', project_issues_path(@project)

app/views/layouts/application.html.haml
!!!
%html
  %head
    -title
    %title #{ yield(:title) } - Falcon
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #container
      %header
        %h1= yield(:title)
        %nav
          %ul
            %li Khaja Minhajuddin
            %li Log Out
      #page
        %section#issue-list
        %section#comments
          %p=notice
          %p=alert
          = yield

app/views/projects/edit.html.haml
%h1 Project#edit
%p Find me in app/views/project/edit.html.haml

app/views/projects/index.html.haml
%h1 Projects

%ul
  - @projects.each do |project|
    %li=link_to project.title, project_issues_path(project)

app/views/projects/new.html.haml
%h1 New Project
= simple_form_for @project do |f|
  .inputs
    = f.input :title, :required => true, :autofocus => true, :placeholder => 'Title'
    = f.input :description, :as => :text, :required => false, :autofocus => true
  .actions
    = f.button :submit

app/views/projects/show.html.haml
%h1= @project.title